[package]
name = "cynthia-macros"
version = "0.0.1"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.7"
syn = { version = "1.0", features = ["full"] }
quote = "1.0"

[dev-dependencies]
cynthia = { version = "0.0.2", path = "../cynthia" }
